---
title: "Identity analysis"
date: "`r Sys.Date()`"
output: 
  html_notebook:
    toc: yes
    code_folding: hide
  md_document:
    variant: gfm 
    toc: yes
---

```{r setup}
library(ggbeeswarm)
library(gt)
source(here::here("src/common_basis.R"))
```


# Different -cels
 
```{r}
cel_post_contents <- incel_posts_cleaned_a %>% 
  filter(str_detect(post_text,"cels?\\b")) %>% 
  select(post_id, post_content=post_text) %>% 
  collect() 

cels_by_post <- cel_post_contents %>%
  mutate(cel=str_extract_all(post_content, "(?<! expand...)[^ \\n]+ cels?\\b|[^ \\n]*cels?\\b(?! said)(?!\\.is)")) %>%
  unnest(cel) %>% 
  filter(!str_detect(cel, "^@")) %>%
  select(post_id, cel) %>% 
  mutate(cel=cel %>% 
           str_to_lower() %>% 
           str_replace_all("\\W","") %>% 
           str_replace_all("s$",""))
```
 
 
```{r}
cels <- cels_by_post %>%
  count(cel) %>% 
  arrange(desc(n))
```
 
```{r}
cels %>% 
  write_tsv(here("data/output/jiemakel/cels.tsv"),na="",quote="needed")
```

```{r}
cels %>%
  head(n=100) %>%
  gt(rowname_col="cel") %>%
  fmt_integer(n)
```
 
```{r}
cels2 <- cels_by_post %>%
  filter(cel!="incel") %>%
  distinct() %>%
  group_by(post_id) %>%
  filter(n()>1) %>%
  arrange(cel) %>%
  summarise(cel=str_flatten(cel, collapse=", "), .groups="drop") %>%
  count(cel) %>% 
  arrange(desc(n))
```
 
```{r}
cels2 %>% 
  write_tsv(here("data/output/jiemakel/cels2.tsv"),na="",quote="needed")
```
 
```{r}
cels2 %>%
  head(n=100) %>%
gt(rowname_col="cel") %>%
  fmt_integer(n)
```
 
```{r}
trucel_posts <- cels_by_post %>% 
  filter(str_detect(cel,"tru")) %>%
  distinct(post_id)

fakecel_posts <- cels_by_post %>% 
  filter(str_detect(cel,"fake")) %>%
  distinct(post_id)
```
 
```{r}
cels_by_post %>% inner_join(trucel_posts, join_by(post_id)) %>%
  filter(!cel %in% c("trucel","truecel", "incel", "httpsincel")) %>%
  count(cel) %>%
  arrange(desc(n))

cels_by_post %>% inner_join(fakecel_posts, join_by(post_id)) %>%
  filter(!cel %in% c("fakecel","incel", "httpsincel")) %>%
  count(cel) %>%
  arrange(desc(n))
```

# Ethnic vs racist

```{r}
far_right_cels <- c("stormfrontcel","nazicel","strormfrontcel","altrightcel","nationalistcel","stromfrontcel","antisemiticcel","rightcel","antisemeticcel","whitecel","jewcel","negroidcel","whitenationalistcel","kebabcel")
ethnic_cels <- c("ethniccel","blackcel","ricecel","currycel","ethnicel","muslimcel","arabcel","browncel","spanishcel","africancel","thaicel","persiancel","polecel","pakicel")
racist_keywords <- c("kike","nigger","nigga","whitey","blm","BLM","cumskin","jew","negroid","kebabcel")
```

```{r, eval=FALSE}
far_right_regexp <- str_flatten(far_right_cels, collapse="|")
incel_far_right_posts <- incel_posts_cleaned_a %>%
  filter(str_detect(post_text, far_right_regexp)) %>%
  inner_join(incel_posts_a, join_by(post_id)) %>%
  compute_a(name="incel_far_right_posts", temporary=FALSE, overwrite=TRUE, unique_indexes=list(c("post_id")), indexes=list(c("thread_id")))
ethnic_regexp <- str_flatten(ethnic_cels, collapse="|")
incel_ethnic_posts <- incel_posts_cleaned_a %>%
  filter(str_detect(post_text, ethnic_regexp)) %>%
  inner_join(incel_posts_a, join_by(post_id)) %>%
  compute_a(name="incel_ethnic_posts", temporary=FALSE, overwrite=TRUE, unique_indexes=list(c("post_id")), indexes=list(c("thread_id")))
racist_regexp <- str_flatten(racist_keywords, collapse="|")
incel_racist_posts <- incel_posts_cleaned_a %>%
  filter(str_detect(post_text, racist_regexp)) %>%
  inner_join(incel_posts_a, join_by(post_id)) %>%
  compute_a(name="incel_racist_posts", temporary=FALSE, overwrite=TRUE, unique_indexes=list(c("post_id")), indexes=list(c("thread_id")))
```

```{r}
incel_far_right_posts %>% 
  anti_join(incel_ethnic_posts, join_by(post_id)) %>%
  anti_join(incel_racist_posts, join_by(post_id)) %>%
  summarise(posts=n(),threads=n_distinct(thread_id), posters=n_distinct(poster_id)) %>%
  mutate(posts_per_thread=posts/threads, posts_per_user=posts/posters, users_per_thread=posters/threads)

incel_ethnic_posts %>% 
  anti_join(incel_far_right_posts, join_by(post_id)) %>%
  anti_join(incel_racist_posts, join_by(post_id)) %>%
  summarise(posts=n(),threads=n_distinct(thread_id), posters=n_distinct(poster_id)) %>%
  mutate(posts_per_thread=posts/threads, posts_per_user=posts/posters, users_per_thread=posters/threads)

incel_racist_posts %>% 
  anti_join(incel_far_right_posts, join_by(post_id)) %>%
  anti_join(incel_ethnic_posts, join_by(post_id)) %>%
  summarise(posts=n(),threads=n_distinct(thread_id), posters=n_distinct(poster_id)) %>%
  mutate(posts_per_thread=posts/threads, posts_per_user=posts/posters, users_per_thread=posters/threads)

```


```{r}
incel_far_right_posts %>% 
  anti_join(incel_ethnic_posts, join_by(post_id)) %>%
  anti_join(incel_racist_posts, join_by(post_id)) %>%
  mutate(type="far_right") %>%
  union_all(
    incel_ethnic_posts %>% 
      anti_join(incel_far_right_posts, join_by(post_id)) %>%
      anti_join(incel_racist_posts, join_by(post_id)) %>%
      mutate(type="ethnic")
  ) %>%
  union_all(
    incel_racist_posts %>% 
      anti_join(incel_ethnic_posts, join_by(post_id)) %>%
      anti_join(incel_far_right_posts, join_by(post_id)) %>%
      mutate(type="racist")
  ) %>%
  count(type,thread_id,name="flagged_posts") %>%
  inner_join(incel_threads_a %>% select(thread_id, total_posts=posts), join_by(thread_id)) %>%
  mutate(flagged_proportion=flagged_posts/total_posts) %>%
  ggplot(aes(x=type,y=flagged_proportion)) +
  geom_quasirandom() +
  theme_hsci_discrete()
```

```{r}
incel_racist_posters <- incel_racist_posts %>% 
  anti_join(incel_ethnic_posts, join_by(post_id)) %>%
  anti_join(incel_far_right_posts, join_by(post_id)) %>%
  distinct(poster_id)

incel_ethnic_posters <- incel_ethnic_posts %>% 
  anti_join(incel_racist_posts, join_by(post_id)) %>%
  anti_join(incel_far_right_posts, join_by(post_id)) %>%
  distinct(poster_id)

incel_far_right_posters <- incel_far_right_posts %>% 
  anti_join(incel_ethnic_posts, join_by(post_id)) %>%
  anti_join(incel_racist_posts, join_by(post_id)) %>%
  distinct(poster_id)
```

```{r}
incel_ethnic_posters %>% 
  inner_join(incel_racist_posters) %>% 
  count()

incel_ethnic_posters %>% 
  anti_join(incel_racist_posters) %>% 
  count()

incel_racist_posters %>%
  anti_join(incel_ethnic_posters) %>% 
  count()

```


```{r}
incel_ethnic_posters %>% 
  inner_join(incel_posts_a) %>% 
  summarise(posts=n(),threads=n_distinct(thread_id))
```

```{r}
incel_racist_posters %>% 
  inner_join(incel_posts_a) %>% 
  summarise(posts=n(),threads=n_distinct(thread_id))
```

# You/we/they are
```{r}
are_post_contents <- incel_posts_cleaned_a %>% 
  filter(str_detect(post_text,"(you|they|we)('re| are) ")) %>% 
  select(post_id, post_text) %>% 
  collect() %>%
  mutate(post_content = post_text %>% str_replace_all("Click to expand...",".") %>% str_replace_all("\\s+"," "))
```


```{r}
ares_by_post <- c(1:6) %>% 
  map_dfr(~are_post_contents %>%
    mutate(length= .x, are=str_extract_all(post_content, str_c("(you|they|we)('re| are)('nt| not)?( a| an| the)?", strrep(" \\w+",.x))))
  ) %>%  
  unnest(are) %>%
  select(post_id, are, length) %>%
  mutate(are=are %>% str_replace("'re"," are") %>% str_replace("'nt", " not")) %>%
  mutate(
    who=str_replace(are," .*",""), 
    are=str_replace(are, ".*? ",""),
    stem=str_replace(are, " [^ ]*$", "")
  ) %>%
  relocate(post_id, length, who, are)
ares_by_post
```


```{r}
ares_by_post_count <- ares_by_post %>%
  count(length, who, are, stem)
ares_by_post_count
```
```{r}
roots <- tribble(
  ~stem,~are,~n,
  "R","they",1,
  "R","we",1,
  "R","you",1,
  "they","they are",1,
  "they are", "they are a",1,
  "they are", "they are the",1,
  "we","we are",1,
  "we are", "we are a",1,
  "we are", "we are the",1,
  "we are", "we are not",1,
  "we are not", "we are not the",1,
  "you","you are",1,
  "you are","you are a",1,
  "you are","you are an",1,
  "you are","you are white or black but",1,
  "you are","you are not",1,
  "you are","you are the",1,
  "you are not","you are not a",1,
  "you are not","you are not an",1,
  "you are not","you are not the",1)
ftree <- ares_by_post_count %>% mutate(stem=str_to_lower(str_c(who," ", stem)), are=str_to_lower(str_c(who, " ", are))) %>% group_by(stem,are) %>% summarise(n=sum(n),.groups="drop")
tree <- ftree %>% filter((str_detect(are,"^you") & n>=200) | (str_detect(are,"^we") & n>25) | (str_detect(are,"^they") & n>=100)) %>% distinct(stem,are,n)
#tree <- tree %>% anti_join(tree %>% inner_join(tree,join_by(are==stem)) %>% group_by(stem) %>% filter(n()==1),join_by(stem))
#tree <- tree %>% anti_join(tree %>% inner_join(tree,join_by(are==stem)) %>% group_by(stem) %>% filter(n()==1),join_by(stem))
#tree <- tree %>% anti_join(tree %>% anti_join(tree, join_by(stem==are)),join_by(are))
#tree <- tree %>% anti_join(tree, join_by(stem==are))
tree <- tree %>% union(ftree %>% filter(stem %in% (tree %>% anti_join(tree, join_by(are==stem)))$are,(str_detect(are,"^you") & n>=20) | (str_detect(are,"^we") & n>10) | (str_detect(are,"^they") & n>=20)) %>% select(stem,are,n))
tree <- tree %>% union(ftree %>% filter(stem %in% (tree %>% anti_join(tree, join_by(are==stem)))$are,(str_detect(are,"^you") & n>=20) | (str_detect(are,"^we") & n>10) | (str_detect(are,"^they") & n>=20)) %>% select(stem,are,n))
tree <- tree %>% union(ftree %>% filter(stem %in% (tree %>% anti_join(tree, join_by(are==stem)))$are,(str_detect(are,"^you") & n>=20) | (str_detect(are,"^we") & n>10) | (str_detect(are,"^they") & n>=20)) %>% select(stem,are,n))
tree <- tree %>% union(ftree %>% filter(stem %in% (tree %>% anti_join(tree, join_by(are==stem)))$are,(str_detect(are,"^you") & n>=20) | (str_detect(are,"^we") & n>10) | (str_detect(are,"^they") & n>=20)) %>% select(stem,are,n))
tree <- roots %>% anti_join(tree, join_by(stem,are)) %>% union(tree)
tree <- tree %>% mutate(label=are) %>% relocate(stem,are,label)
tree %>% anti_join(tree,join_by(stem==are))
```

```{r}
library(treeio)
library(ggtree)
```


```{r}
tree %>% filter(str_detect(label,"^you")) %>% as.phylo() %>% ggtree(layout='circular') %<+% (tree %>% select(are,n)) + geom_tiplab(aes(size=n),show.legend = FALSE) + 
  theme_tree(plot.margin=margin(90, 10, 90, 10))

tree %>% filter(str_detect(label,"^we")) %>% as.phylo() %>% ggtree(layout='circular') %<+% (tree %>% select(are,n)) + geom_tiplab(aes(size=n),show.legend = FALSE) + 
  theme_tree(plot.margin=margin(90, 10, 90, 10))

tree %>% filter(str_detect(label,"^they")) %>% as.phylo() %>% ggtree(layout='circular') %<+% (tree %>% select(are,n)) +
  geom_tiplab(aes(size=n),show.legend = FALSE) + 
  theme_tree(plot.margin=margin(90, 10, 90, 10))
```

```{r}
top_ares <- ares_by_post_count %>% 
  group_by(length, who) %>%
  slice_max(n,n=20) %>%
  ungroup()
```


```{r}
ares_by_post_count %>% 
#  anti_join(top_ares, join_by(who, are==stem)) %>%
  anti_join(ares_by_post_count %>% mutate(length=length+1), join_by(who,are,length)) %>%
  select(-stem) %>%
  group_by(length, who) %>%
  slice_max(n,n=20) %>%
  mutate(order=row_number()) %>%
  ungroup() %>%
  filter(order<=20) %>%
  pivot_wider(id_cols=c("length","order"), names_from="who", values_from=c("are","n")) %>%
  relocate(are_they,n_they,are_we,n_we,are_you,n_you) %>%
  arrange(desc(length)) %>%
  gt(groupname_col = "length", rowname_col="order") %>%
  cols_label(
    are_they="They",
    n_they="N",
    are_we="We",
    n_we="N",
    are_you="You",
    n_you="N") %>%
  tab_style(
    style = list(
      cell_borders(
        sides = c("right"),
        style = "solid"
      )
    ),
    locations = cells_body(
      columns = c(n_we,n_you,n_they)
    )
  )
  
```

