---
title: "Incel analysis test"
date: "`r Sys.Date()`"
output: 
  md_document:
    variant: gfm 
    toc: yes
  html_notebook:
    toc: yes
    code_folding: hide
---

```{r setup}
library(ggbeeswarm)
library(dplyr)
library(gt)
source(here::here("src/common_basis.R"))
```

```{r}

incel_quotes_c %>% filter(quoted_post_id==0)

```


```{r}
incel_top_quoted = incel_quotes_c %>% filter(quoted_post_id!=0) %>%
  group_by(quoted_post_id) %>%tally(sort =TRUE) %>% collect() %>% rename(number_of_replies = n)
incel_top_quoted
```


```{r}
# incel_posts_local <- incel_posts_c %>% collect()
```

```{r}

by <- join_by(quoted_post_id == post_id)
top_quoted_posts <- left_join(incel_top_quoted, incel_posts_local, by) 
top_quoted_posts

```
```{r}
top_quoted_posts<- top_quoted_posts %>% filter(number_of_replies>2)

top_quoted_posts["reply_post_order_ratio"] <- top_quoted_posts$number_of_replies*top_quoted_posts$post_order_in_thread 

top_quoted_posts

```


```{r}

library(purrr)
library(rvest)

top_quoted_posts['cleaned_text'] <- map_chr(top_quoted_posts$post_html, function(x) {
  x <- read_html(x)
  div <- html_nodes(x, "div.bbWrapper")
  strings <- html_text(div, trim = TRUE)
  paste(strings, collapse = " ")
})


top_quoted_posts
```
```{r}
# write_tsv(top_quoted_posts, "top_quoted_posts.tsv", quote="needed", na="")
```

```{r}
top_quoted_posts['wordcount'] <- str_count(top_quoted_posts$cleaned_text, '\\w+')
top_quoted_posts

```


```{r}
wordcount_graph <- ggplot(top_quoted_posts, aes(x=wordcount,y=number_of_replies)) +
  geom_point(color="#330099") +
  coord_cartesian(xlim = c(0, 1100), ylim = c(3, 25), expand = FALSE) +
  scale_y_continuous(breaks = c(3, 5, 10, 15, 20, 25)) + 
  xlab("Wordcount") +
  ylab("Number of replies") +
  theme_hsci_discrete()

wordcount_graph
```



```{r}
 post_order_graph <- ggplot(top_quoted_posts, aes(x=post_order_in_thread,y=number_of_replies)) +
  geom_point(color="#ff0066") +
  coord_cartesian(xlim=c(0, 2600), ylim = c(3, 25), expand = FALSE) +
  scale_y_continuous(breaks = c(3, 5, 10, 15, 20, 25)) + 
  xlab("Post order in thread") +
  ylab("Number of replies") +
  theme_hsci_discrete()

post_order_graph

```

```{r}
weighted_replies_graph <- ggplot(top_quoted_posts, aes(x=wordcount,y=reply_post_order_ratio)) +
  geom_point() +
  coord_cartesian(xlim=c(0, 501), expand = FALSE) +
  scale_y_continuous(labels=scales::number) + 
  xlab("Wordcount") +
  ylab("Number of replies * position in thread") +
  theme_hsci_discrete()

weighted_replies_graph

```

```{r}


more_replies_than_expected <- arrange(top_quoted_posts, desc(reply_post_order_ratio)) %>% filter(reply_post_order_ratio>200) 


# write_tsv(more_replies_than_expected, "more_replies_than_expected.tsv", quote="needed", na="")

more_replies_than_expected

```
```{r}
engaging_threads <- more_replies_than_expected %>% filter(post_order_in_thread>1) %>% filter(wordcount>20) %>% group_by(thread_id) %>% tally(sort=TRUE)

# incel_threads_local <- incel_threads_c %>% collect()

engaging_threads_10 <- engaging_threads %>% filter(row_number() %in% 1:10) %>% left_join(incel_threads_local)

engaging_threads_10


```
```{r}
engaging_threads_weighted <- more_replies_than_expected  %>%  filter(post_order_in_thread>1) %>% filter(wordcount>20) %>% group_by(thread_id) %>% tally(sort=TRUE, wt=reply_post_order_ratio) %>% rename(karma_sum = n) %>% left_join(incel_threads_local)

engaging_threads_weighted["karma_avg"] <- engaging_threads_weighted$karma_sum / engaging_threads_weighted$posts

engaging_threads_weighted %>% arrange(desc(karma_avg))
```
```{r}
engaging_threads_graph <- ggplot(engaging_threads_weighted, aes(x=posts,y=karma_avg)) +
  geom_point() +
  coord_cartesian(xlim=c(0, 2000), expand = FALSE) +
  scale_y_continuous(labels=scales::number) + 
  scale_x_continuous() +
  xlab("Posts in thread") +
  ylab("Thread 'karma'") +
  theme_hsci_discrete()

engaging_threads_graph
```


```{r}
engaging_users <- more_replies_than_expected %>% filter(post_order_in_thread>1) %>% filter(wordcount>20) %>% group_by(poster_id) %>% tally(sort=TRUE) %>% rename(karma =n)


# incel_users_local <- incel_users_c %>% collect()

by <- join_by(poster_id == user_id)

engaging_users <- engaging_users %>% left_join(incel_users_local, by)
engaging_users


median(incel_users_local$user_total_posts)
```

```{r}

engaging_users_weighted <- more_replies_than_expected %>% filter(post_order_in_thread>1) %>% filter(wordcount>20) %>% group_by(poster_id) %>% tally(sort=TRUE, wt=reply_post_order_ratio) %>% rename(karma = n)

by <- join_by(poster_id == user_id)

engaging_users_weighted <- engaging_users_weighted  %>% left_join(incel_users_local, by)
engaging_users_weighted


```
```{r}
engaging_users_graph <- ggplot(engaging_users_weighted, aes(x=user_total_posts,y=karma)) +
  geom_point() +
  coord_cartesian(xlim=c(0, 10000), expand = FALSE) +
  scale_y_continuous(labels=scales::number) + 
  scale_x_continuous() +
  xlab("User's total post number") +
  ylab("Reply 'karma'") +
  theme_hsci_discrete()

engaging_users_graph
```
```{r}
engaging_users_weighted %>% filter(karma>5000)
```
```{r}
poster_thread_groups <- incel_posts_local %>% group_by(thread_id, poster_id) %>% tally(sort=TRUE) %>% filter(n>5)

threads_with_lots_of_posters <- poster_thread_groups %>% group_by(thread_id) %>% tally(sort=TRUE) %>% filter(n>10)

```
```{r}

threads_with_lots_of_posters <- threads_with_lots_of_posters %>%  left_join(incel_threads_local)
threads_with_lots_of_posters

```






```{r}
by <- join_by(post_id == quoted_post_id)
short_thread_posts <- incel_threads_local %>% filter(posts<=100) %>% left_join(incel_posts_local) %>% inner_join(incel_top_quoted, by)
short_thread_posts

```
```{r}
short_thread_posts["reply_post_order_ratio"] <- short_thread_posts$number_of_replies*short_thread_posts$post_order_in_thread 
short_thread_posts  %>% filter(number_of_replies>1) %>% arrange(desc(reply_post_order_ratio))

short_threads_user_counts <- short_thread_posts %>% group_by(thread_id) %>% summarise(users_posting = n_distinct(poster_id))

# short_threads_mean_karma <- short_thread_posts  %>% group_by(thread_id) %>%  summarise(mean_karma=mean(reply_post_order_ratio),                  .groups = 'drop') %>% arrange(desc(mean_karma)) 
short_threads_sum_karma <- short_thread_posts  %>% group_by(thread_id) %>% tally(wt=reply_post_order_ratio) %>% rename(karma_sum = n) 

short_threads <- short_threads_sum_karma %>% left_join(incel_threads_local)%>% left_join(short_threads_user_counts)
short_threads["karma_avg"] <- short_threads["karma_sum"] / short_threads["posts"]

short_threads

```
```{r}
short_thread_posts %>% filter)
  
```

```{r}
engaging_short_threads_graph <- ggplot(short_threads, aes(x=users_posting, y=karma_avg, colour=posts)) + geom_point() + 
annotate("text", x = 34	, y = 25, label = "B") +
annotate("text", x = 5	, y = 44.5, label = "A") +
annotate("text", x = 1	, y = -1, label = "C") + 
theme_hsci_continuous() +
  theme(legend.position = c(0.8, 0.25)) +
xlab("Users participating") +
ylab("Reply factor")

# + geom_text(aes(label = thread_title), size = 3)

engaging_short_threads_graph

# A: Reddit faggotcel picking up fresh shit from his boyfriend's butt-hole, sniffs, tastes it and then cries" <-shock post, lots of users commenting that it's gross (34 users, 94 posts) https://incels.is/threads/reddit-faggotcel-picking-up-fresh-shit-from-his-boyfriends-butt-hole-sniffs-tastes-it-and-then-cries.113201/	

# B: [Music] Staind's Tormented Album <- on topic, OP engages with other posters the most (5 users, 92 posts) https://incels.is/threads/music-stainds-tormented-album.174980/
# C: Who do you talk to in real life? (1 poster, 28 posts) 	https://incels.is/threads/who-do-you-talk-to-in-real-life.139868/
```
```{r}
png("poster_plot.png", units="in", width=10, height=6, res=300, bg = "transparent")
engaging_short_threads_graph
dev.off()
```



```{r}
short_threads %>% filter( users_posting ==1) %>% arrange(karma_avg)
```

```{r}
fakecels <- read.csv(here::here("data/output/umit/fakecels.csv")) %>% group_by(thread_id) %>% tally(wt=Query.count) %>% rename(fakecel_mentions = n)
short_threads <- short_threads %>% left_join(fakecels)

fakecel_short_threads_graph <- ggplot(short_threads, aes(x=users_posting, y=karma_avg, color=fakecel_mentions)) + geom_point() +  theme_hsci_continuous() 

fakecel_short_threads_graph


```
```
